package com.automotive.carsettings.aidl

/**
 * Property ID constants following Android Automotive VehiclePropertyIds pattern.
 * Property IDs are composed of: type | area | group | specific_id
 */
object PropertyConstants {

    // Type masks (bits 24-27)
    private const val TYPE_MASK = 0x0F000000
    const val TYPE_STRING = 0x00100000
    const val TYPE_BOOLEAN = 0x00200000
    const val TYPE_INT32 = 0x00400000
    const val TYPE_FLOAT = 0x00600000
    const val TYPE_INT32_VEC = 0x00410000
    const val TYPE_FLOAT_VEC = 0x00610000

    // Area type masks (bits 20-23)
    private const val AREA_MASK = 0x00F00000
    const val AREA_GLOBAL = 0x01000000
    const val AREA_SEAT = 0x05000000
    const val AREA_DOOR = 0x06000000
    const val AREA_WINDOW = 0x03000000
    const val AREA_MIRROR = 0x04000000
    const val AREA_WHEEL = 0x07000000

    // Property groups (bits 16-19)
    private const val GROUP_MASK = 0x000F0000
    const val GROUP_DISPLAY = 0x00010000
    const val GROUP_AUDIO = 0x00020000
    const val GROUP_HVAC = 0x00030000
    const val GROUP_VEHICLE = 0x00040000
    const val GROUP_PROFILE = 0x00050000
    const val GROUP_PRIVACY = 0x00060000

    // Display Properties
    const val DISPLAY_BRIGHTNESS = AREA_GLOBAL or TYPE_INT32 or GROUP_DISPLAY or 0x0001
    const val DISPLAY_THEME = AREA_GLOBAL or TYPE_INT32 or GROUP_DISPLAY or 0x0002
    const val DISPLAY_LANGUAGE = AREA_GLOBAL or TYPE_STRING or GROUP_DISPLAY or 0x0003
    const val DISPLAY_NIGHT_MODE = AREA_GLOBAL or TYPE_BOOLEAN or GROUP_DISPLAY or 0x0004
    const val DISPLAY_AUTO_BRIGHTNESS = AREA_GLOBAL or TYPE_BOOLEAN or GROUP_DISPLAY or 0x0005
    const val DISPLAY_SCREEN_TIMEOUT = AREA_GLOBAL or TYPE_INT32 or GROUP_DISPLAY or 0x0006
    const val DISPLAY_FONT_SIZE = AREA_GLOBAL or TYPE_INT32 or GROUP_DISPLAY or 0x0007
    const val DISPLAY_COLOR_INVERSION = AREA_GLOBAL or TYPE_BOOLEAN or GROUP_DISPLAY or 0x0008

    // Audio Properties
    const val AUDIO_VOLUME_MEDIA = AREA_GLOBAL or TYPE_INT32 or GROUP_AUDIO or 0x0001
    const val AUDIO_VOLUME_NAVIGATION = AREA_GLOBAL or TYPE_INT32 or GROUP_AUDIO or 0x0002
    const val AUDIO_VOLUME_CALL = AREA_GLOBAL or TYPE_INT32 or GROUP_AUDIO or 0x0003
    const val AUDIO_VOLUME_VOICE_COMMAND = AREA_GLOBAL or TYPE_INT32 or GROUP_AUDIO or 0x0004
    const val AUDIO_VOLUME_RINGTONE = AREA_GLOBAL or TYPE_INT32 or GROUP_AUDIO or 0x0005
    const val AUDIO_VOLUME_ALARM = AREA_GLOBAL or TYPE_INT32 or GROUP_AUDIO or 0x0006
    const val AUDIO_BALANCE = AREA_GLOBAL or TYPE_INT32 or GROUP_AUDIO or 0x0007
    const val AUDIO_FADE = AREA_GLOBAL or TYPE_INT32 or GROUP_AUDIO or 0x0008
    const val AUDIO_BASS = AREA_GLOBAL or TYPE_INT32 or GROUP_AUDIO or 0x0009
    const val AUDIO_TREBLE = AREA_GLOBAL or TYPE_INT32 or GROUP_AUDIO or 0x000A
    const val AUDIO_EQ_PRESET = AREA_GLOBAL or TYPE_INT32 or GROUP_AUDIO or 0x000B
    const val AUDIO_SURROUND_SOUND = AREA_GLOBAL or TYPE_BOOLEAN or GROUP_AUDIO or 0x000C
    const val AUDIO_SPEED_COMPENSATED_VOLUME = AREA_GLOBAL or TYPE_BOOLEAN or GROUP_AUDIO or 0x000D

    // HVAC Properties
    const val HVAC_TEMPERATURE = AREA_SEAT or TYPE_FLOAT or GROUP_HVAC or 0x0001
    const val HVAC_FAN_SPEED = AREA_SEAT or TYPE_INT32 or GROUP_HVAC or 0x0002
    const val HVAC_FAN_DIRECTION = AREA_SEAT or TYPE_INT32 or GROUP_HVAC or 0x0003
    const val HVAC_AC_ON = AREA_GLOBAL or TYPE_BOOLEAN or GROUP_HVAC or 0x0004
    const val HVAC_AUTO_MODE = AREA_GLOBAL or TYPE_BOOLEAN or GROUP_HVAC or 0x0005
    const val HVAC_RECIRCULATION_ON = AREA_GLOBAL or TYPE_BOOLEAN or GROUP_HVAC or 0x0006
    const val HVAC_DUAL_ZONE = AREA_GLOBAL or TYPE_BOOLEAN or GROUP_HVAC or 0x0007
    const val HVAC_MAX_DEFROST_ON = AREA_GLOBAL or TYPE_BOOLEAN or GROUP_HVAC or 0x0008
    const val HVAC_SEAT_HEATING = AREA_SEAT or TYPE_INT32 or GROUP_HVAC or 0x0009
    const val HVAC_SEAT_VENTILATION = AREA_SEAT or TYPE_INT32 or GROUP_HVAC or 0x000A
    const val HVAC_STEERING_WHEEL_HEAT = AREA_GLOBAL or TYPE_INT32 or GROUP_HVAC or 0x000B
    const val HVAC_DEFROSTER = AREA_WINDOW or TYPE_BOOLEAN or GROUP_HVAC or 0x000C

    // Vehicle Properties
    const val VEHICLE_UNITS_DISTANCE = AREA_GLOBAL or TYPE_INT32 or GROUP_VEHICLE or 0x0001
    const val VEHICLE_UNITS_TEMPERATURE = AREA_GLOBAL or TYPE_INT32 or GROUP_VEHICLE or 0x0002
    const val VEHICLE_UNITS_VOLUME = AREA_GLOBAL or TYPE_INT32 or GROUP_VEHICLE or 0x0003
    const val VEHICLE_UNITS_PRESSURE = AREA_GLOBAL or TYPE_INT32 or GROUP_VEHICLE or 0x0004
    const val VEHICLE_DOOR_LOCK = AREA_DOOR or TYPE_BOOLEAN or GROUP_VEHICLE or 0x0005
    const val VEHICLE_HEADLIGHTS_AUTO = AREA_GLOBAL or TYPE_BOOLEAN or GROUP_VEHICLE or 0x0006
    const val VEHICLE_HEADLIGHTS_ON = AREA_GLOBAL or TYPE_BOOLEAN or GROUP_VEHICLE or 0x0007
    const val VEHICLE_AMBIENT_LIGHT_COLOR = AREA_GLOBAL or TYPE_INT32 or GROUP_VEHICLE or 0x0008
    const val VEHICLE_AMBIENT_LIGHT_BRIGHTNESS = AREA_GLOBAL or TYPE_INT32 or GROUP_VEHICLE or 0x0009
    const val VEHICLE_MIRROR_FOLD = AREA_MIRROR or TYPE_BOOLEAN or GROUP_VEHICLE or 0x000A
    const val VEHICLE_MIRROR_ADJUSTMENT = AREA_MIRROR or TYPE_FLOAT_VEC or GROUP_VEHICLE or 0x000B
    const val VEHICLE_AUTO_PARK_BRAKE = AREA_GLOBAL or TYPE_BOOLEAN or GROUP_VEHICLE or 0x000C

    // Driver Profile Properties
    const val PROFILE_NAME = AREA_GLOBAL or TYPE_STRING or GROUP_PROFILE or 0x0001
    const val PROFILE_AVATAR = AREA_GLOBAL or TYPE_STRING or GROUP_PROFILE or 0x0002
    const val PROFILE_SEAT_POSITION = AREA_SEAT or TYPE_INT32_VEC or GROUP_PROFILE or 0x0003
    const val PROFILE_MIRROR_POSITION = AREA_MIRROR or TYPE_FLOAT_VEC or GROUP_PROFILE or 0x0004
    const val PROFILE_STEERING_POSITION = AREA_GLOBAL or TYPE_INT32_VEC or GROUP_PROFILE or 0x0005
    const val PROFILE_LAST_SELECTED = AREA_GLOBAL or TYPE_INT32 or GROUP_PROFILE or 0x0006

    // Privacy Properties
    const val PRIVACY_LOCATION_ENABLED = AREA_GLOBAL or TYPE_BOOLEAN or GROUP_PRIVACY or 0x0001
    const val PRIVACY_ANALYTICS_ENABLED = AREA_GLOBAL or TYPE_BOOLEAN or GROUP_PRIVACY or 0x0002
    const val PRIVACY_VOICE_DATA_COLLECTION = AREA_GLOBAL or TYPE_BOOLEAN or GROUP_PRIVACY or 0x0003
    const val PRIVACY_PERSONALIZATION_ENABLED = AREA_GLOBAL or TYPE_BOOLEAN or GROUP_PRIVACY or 0x0004
    const val PRIVACY_CAMERA_ENABLED = AREA_GLOBAL or TYPE_BOOLEAN or GROUP_PRIVACY or 0x0005
    const val PRIVACY_MICROPHONE_ENABLED = AREA_GLOBAL or TYPE_BOOLEAN or GROUP_PRIVACY or 0x0006

    // Helper functions
    fun getPropertyType(propertyId: Int): Int {
        return propertyId and TYPE_MASK
    }

    fun getAreaType(propertyId: Int): Int {
        return propertyId and AREA_MASK
    }

    fun getPropertyGroup(propertyId: Int): Int {
        return propertyId and GROUP_MASK
    }

    fun isGlobalProperty(propertyId: Int): Boolean {
        return (propertyId and AREA_MASK) == AREA_GLOBAL
    }

    fun getPropertyName(propertyId: Int): String {
        return when (propertyId) {
            // Display
            DISPLAY_BRIGHTNESS -> "DISPLAY_BRIGHTNESS"
            DISPLAY_THEME -> "DISPLAY_THEME"
            DISPLAY_LANGUAGE -> "DISPLAY_LANGUAGE"
            DISPLAY_NIGHT_MODE -> "DISPLAY_NIGHT_MODE"
            DISPLAY_AUTO_BRIGHTNESS -> "DISPLAY_AUTO_BRIGHTNESS"
            DISPLAY_SCREEN_TIMEOUT -> "DISPLAY_SCREEN_TIMEOUT"
            DISPLAY_FONT_SIZE -> "DISPLAY_FONT_SIZE"
            DISPLAY_COLOR_INVERSION -> "DISPLAY_COLOR_INVERSION"

            // Audio
            AUDIO_VOLUME_MEDIA -> "AUDIO_VOLUME_MEDIA"
            AUDIO_VOLUME_NAVIGATION -> "AUDIO_VOLUME_NAVIGATION"
            AUDIO_VOLUME_CALL -> "AUDIO_VOLUME_CALL"
            AUDIO_VOLUME_VOICE_COMMAND -> "AUDIO_VOLUME_VOICE_COMMAND"
            AUDIO_VOLUME_RINGTONE -> "AUDIO_VOLUME_RINGTONE"
            AUDIO_VOLUME_ALARM -> "AUDIO_VOLUME_ALARM"
            AUDIO_BALANCE -> "AUDIO_BALANCE"
            AUDIO_FADE -> "AUDIO_FADE"
            AUDIO_BASS -> "AUDIO_BASS"
            AUDIO_TREBLE -> "AUDIO_TREBLE"
            AUDIO_EQ_PRESET -> "AUDIO_EQ_PRESET"
            AUDIO_SURROUND_SOUND -> "AUDIO_SURROUND_SOUND"
            AUDIO_SPEED_COMPENSATED_VOLUME -> "AUDIO_SPEED_COMPENSATED_VOLUME"

            // HVAC
            HVAC_TEMPERATURE -> "HVAC_TEMPERATURE"
            HVAC_FAN_SPEED -> "HVAC_FAN_SPEED"
            HVAC_FAN_DIRECTION -> "HVAC_FAN_DIRECTION"
            HVAC_AC_ON -> "HVAC_AC_ON"
            HVAC_AUTO_MODE -> "HVAC_AUTO_MODE"
            HVAC_RECIRCULATION_ON -> "HVAC_RECIRCULATION_ON"
            HVAC_DUAL_ZONE -> "HVAC_DUAL_ZONE"
            HVAC_MAX_DEFROST_ON -> "HVAC_MAX_DEFROST_ON"
            HVAC_SEAT_HEATING -> "HVAC_SEAT_HEATING"
            HVAC_SEAT_VENTILATION -> "HVAC_SEAT_VENTILATION"
            HVAC_STEERING_WHEEL_HEAT -> "HVAC_STEERING_WHEEL_HEAT"
            HVAC_DEFROSTER -> "HVAC_DEFROSTER"

            // Vehicle
            VEHICLE_UNITS_DISTANCE -> "VEHICLE_UNITS_DISTANCE"
            VEHICLE_UNITS_TEMPERATURE -> "VEHICLE_UNITS_TEMPERATURE"
            VEHICLE_UNITS_VOLUME -> "VEHICLE_UNITS_VOLUME"
            VEHICLE_UNITS_PRESSURE -> "VEHICLE_UNITS_PRESSURE"
            VEHICLE_DOOR_LOCK -> "VEHICLE_DOOR_LOCK"
            VEHICLE_HEADLIGHTS_AUTO -> "VEHICLE_HEADLIGHTS_AUTO"
            VEHICLE_HEADLIGHTS_ON -> "VEHICLE_HEADLIGHTS_ON"
            VEHICLE_AMBIENT_LIGHT_COLOR -> "VEHICLE_AMBIENT_LIGHT_COLOR"
            VEHICLE_AMBIENT_LIGHT_BRIGHTNESS -> "VEHICLE_AMBIENT_LIGHT_BRIGHTNESS"
            VEHICLE_MIRROR_FOLD -> "VEHICLE_MIRROR_FOLD"
            VEHICLE_MIRROR_ADJUSTMENT -> "VEHICLE_MIRROR_ADJUSTMENT"
            VEHICLE_AUTO_PARK_BRAKE -> "VEHICLE_AUTO_PARK_BRAKE"

            // Profile
            PROFILE_NAME -> "PROFILE_NAME"
            PROFILE_AVATAR -> "PROFILE_AVATAR"
            PROFILE_SEAT_POSITION -> "PROFILE_SEAT_POSITION"
            PROFILE_MIRROR_POSITION -> "PROFILE_MIRROR_POSITION"
            PROFILE_STEERING_POSITION -> "PROFILE_STEERING_POSITION"
            PROFILE_LAST_SELECTED -> "PROFILE_LAST_SELECTED"

            // Privacy
            PRIVACY_LOCATION_ENABLED -> "PRIVACY_LOCATION_ENABLED"
            PRIVACY_ANALYTICS_ENABLED -> "PRIVACY_ANALYTICS_ENABLED"
            PRIVACY_VOICE_DATA_COLLECTION -> "PRIVACY_VOICE_DATA_COLLECTION"
            PRIVACY_PERSONALIZATION_ENABLED -> "PRIVACY_PERSONALIZATION_ENABLED"
            PRIVACY_CAMERA_ENABLED -> "PRIVACY_CAMERA_ENABLED"
            PRIVACY_MICROPHONE_ENABLED -> "PRIVACY_MICROPHONE_ENABLED"

            else -> "UNKNOWN_PROPERTY_$propertyId"
        }
    }

    fun getAllPropertyIds(): IntArray {
        return intArrayOf(
            // Display
            DISPLAY_BRIGHTNESS, DISPLAY_THEME, DISPLAY_LANGUAGE, DISPLAY_NIGHT_MODE,
            DISPLAY_AUTO_BRIGHTNESS, DISPLAY_SCREEN_TIMEOUT, DISPLAY_FONT_SIZE, DISPLAY_COLOR_INVERSION,

            // Audio
            AUDIO_VOLUME_MEDIA, AUDIO_VOLUME_NAVIGATION, AUDIO_VOLUME_CALL, AUDIO_VOLUME_VOICE_COMMAND,
            AUDIO_VOLUME_RINGTONE, AUDIO_VOLUME_ALARM, AUDIO_BALANCE, AUDIO_FADE,
            AUDIO_BASS, AUDIO_TREBLE, AUDIO_EQ_PRESET, AUDIO_SURROUND_SOUND, AUDIO_SPEED_COMPENSATED_VOLUME,

            // HVAC
            HVAC_TEMPERATURE, HVAC_FAN_SPEED, HVAC_FAN_DIRECTION, HVAC_AC_ON,
            HVAC_AUTO_MODE, HVAC_RECIRCULATION_ON, HVAC_DUAL_ZONE, HVAC_MAX_DEFROST_ON,
            HVAC_SEAT_HEATING, HVAC_SEAT_VENTILATION, HVAC_STEERING_WHEEL_HEAT, HVAC_DEFROSTER,

            // Vehicle
            VEHICLE_UNITS_DISTANCE, VEHICLE_UNITS_TEMPERATURE, VEHICLE_UNITS_VOLUME, VEHICLE_UNITS_PRESSURE,
            VEHICLE_DOOR_LOCK, VEHICLE_HEADLIGHTS_AUTO, VEHICLE_HEADLIGHTS_ON, VEHICLE_AMBIENT_LIGHT_COLOR,
            VEHICLE_AMBIENT_LIGHT_BRIGHTNESS, VEHICLE_MIRROR_FOLD, VEHICLE_MIRROR_ADJUSTMENT, VEHICLE_AUTO_PARK_BRAKE,

            // Profile
            PROFILE_NAME, PROFILE_AVATAR, PROFILE_SEAT_POSITION, PROFILE_MIRROR_POSITION,
            PROFILE_STEERING_POSITION, PROFILE_LAST_SELECTED,

            // Privacy
            PRIVACY_LOCATION_ENABLED, PRIVACY_ANALYTICS_ENABLED, PRIVACY_VOICE_DATA_COLLECTION,
            PRIVACY_PERSONALIZATION_ENABLED, PRIVACY_CAMERA_ENABLED, PRIVACY_MICROPHONE_ENABLED
        )
    }
}
